#FSR Autogenerated Content. DO NOT DELETE
from .get_alert_list import get_alert_list
from .get_device_group_list import get_device_group_list
from .get_device_list import get_device_list
from .get_device_alerts import get_device_alerts
from .get_report_list import get_report_list
from .get_report_by_id import get_report_by_id
 
supported_operations = {'get_alert_list': get_alert_list, 'get_device_group_list': get_device_group_list, 'get_device_list': get_device_list, 'get_device_alerts': get_device_alerts, 'get_report_list': get_report_list, 'get_report_by_id': get_report_by_id, }